"""Build an opt-in precision-patched SDK copy for ONLYOFFICE 9.3.1 build 10.

Copy mode never modifies the input or running DocumentServer. Image-install mode
is only for an isolated Docker build, never a running server. Serve the output on
an isolated test proxy until live edit/save/reopen and preservation audits pass.
Server V8 snapshots (slide/sdk-all.bin) bypass this JS: replacing JS/cache alone
has no effect there. Disable the snapshot only on an isolated experiment server.
Not deployed to production; see docs/office-save-fixes.md for validation scope.
Anchors correspond to sdkjs common/Shapes/{Serialize,SerializeWriter}.js at
v9.3.1.10 (72d49bfa2b59dd328efcc2c3b20f5b1e5e4bc5a3).
"""

from __future__ import annotations

import argparse
import gzip
import hashlib
import json
from pathlib import Path

SDK_HASH = "5c1a4d91a185fbb6ff09a68b839d7891a89d918db1f12d2a88d03e9ee823fbd8"
REPLACEMENTS = (
    # Keep hundredths of a point on import instead of rounding to half-points.
    (b"t=p.Ya()/100;t=2*t+.5>>0;t/=2;k.Jb=t;k.Pj=t;", b"t=p.Ya()/100;k.Jb=t;k.Pj=t;"),
    # Millimetres/radians -> integer OOXML units: nearest, not truncation to zero.
    (
        b"this.Pza=function(x,B,N){null!=B&&this.Mp(x,B*N>>0)}",
        b"this.Pza=function(x,B,N){null!=B&&this.Mp(x,Math.round(B*N))}",
    ),
    # Paragraph percentage and point spacing use the same integer conversion rule.
    (b"r.Mp(0,1E5*N.tc>>0)", b"r.Mp(0,Math.round(1E5*N.tc))"),
    (b"T=N.tc/.00352777778>>0", b"T=Math.round(N.tc/.00352777778)"),
    (b"T=N.nh/.00352777778>>0", b"T=Math.round(N.nh/.00352777778)"),
    (b"T=N.Zk/.00352777778>>0", b"T=Math.round(N.Zk/.00352777778)"),
    (
        b"N=100*x.Jb,N=Math.max(100,N),r.Mp(17,N)",
        b"N=Math.round(100*x.Jb),N=Math.max(100,N),r.Mp(17,N)",
    ),
)


def transform(data: bytes) -> bytes:
    """Fail closed on every unrecognised byte, including partially applied patches."""
    canonical = data.replace(
        b"this.O_i=new AscCommon.hpf(16,B);", b"this.O_i=new AscCommon.hpf(40,B);"
    )
    if hashlib.sha256(canonical).hexdigest() != SDK_HASH:
        raise ValueError("Unsupported ONLYOFFICE SDK; output not written")
    for before, _ in REPLACEMENTS:
        if data.count(before) != 1:
            raise ValueError("SDK anchor is absent or ambiguous; output not written")
    for before, after in REPLACEMENTS:
        data = data.replace(before, after)
    return data


def build(source: Path, output: Path) -> str:
    patched = transform(source.read_bytes())
    # Refuse overwriting source, historical artifacts or an existing patch output.
    with output.open("xb") as target:
        target.write(patched)
    return hashlib.sha256(patched).hexdigest()


MANIFEST = "precision-manifest.json"
SDK_FILE = "sdk-all.js"
SNAPSHOTS = ("sdk-all.bin", "sdk-all.bin.gz")
CACHES = ("sdk-all.cache", "sdk-all.cache.gz")


def supported_hashes() -> dict[str, str]:
    """Pin both supported inputs, preserving the independent rendering interval."""
    rendering_source = "5ad873396344deedf33b03fb81a1b0421108ac4d7160dd58b6ca6d77c7ee90e7"
    rendering_patched = "59a12980323c12e539c3d513c9e3802a685d8e9f967d8d09c818dd03712f8770"
    return {
        SDK_HASH: "d128187c2e1f41061ed04caad67d3321c8143f238eccb90b727e8d499759098d",
        rendering_source: rendering_patched,
    }


def install(directory: Path) -> dict[str, str]:
    """Image-build only. Never call against a running DocumentServer."""
    manifest = directory / MANIFEST
    if manifest.exists():
        raise FileExistsError(manifest)
    for name in (SDK_FILE, SDK_FILE + ".gz", *SNAPSHOTS, *CACHES, MANIFEST):
        if (directory / name).is_symlink():
            raise ValueError(f"Refusing symlink: {name}")
    source = (directory / SDK_FILE).read_bytes()
    patched = transform(source)
    before = hashlib.sha256(source).hexdigest()
    after = hashlib.sha256(patched).hexdigest()
    if supported_hashes().get(before) != after:
        raise ValueError("Unsupported precision output; image not patched")
    report = {"source_sha256": before, "patched_sha256": after}
    # Validation above is read-only. A failed Docker RUN never publishes an image layer.
    (directory / SDK_FILE).write_bytes(patched)
    (directory / (SDK_FILE + ".gz")).write_bytes(gzip.compress(patched, mtime=0))
    for name in (*SNAPSHOTS, *CACHES):
        (directory / name).unlink(missing_ok=True)
    with manifest.open("x") as target:
        json.dump(report, target, indent=2)
    verify_install(directory)
    return report


def verify_install(directory: Path, *, clear_cache: bool = False) -> dict[str, str]:
    """Fail closed on drift; optionally discard V8 code cache before server start.

    Startup regenerates gzip, so compare decoded bytes, not gzip headers. Code cache
    may be regenerated by the converter; snapshots must remain absent at all times.
    """
    loaded = json.loads((directory / MANIFEST).read_text())
    if not isinstance(loaded, dict) or not all(
        isinstance(k, str) and isinstance(v, str) for k, v in loaded.items()
    ):
        raise ValueError("Unsupported precision manifest")
    report: dict[str, str] = loaded
    expected = supported_hashes().get(report.get("source_sha256", ""))
    if expected is None or report.get("patched_sha256") != expected:
        raise ValueError("Unsupported precision manifest")
    for name in (SDK_FILE, SDK_FILE + ".gz", MANIFEST, *SNAPSHOTS, *CACHES):
        if (directory / name).is_symlink():
            raise ValueError(f"Refusing symlink: {name}")
    data = (directory / SDK_FILE).read_bytes()
    if hashlib.sha256(data).hexdigest() != expected:
        raise ValueError("Precision SDK hash mismatch")
    if gzip.decompress((directory / (SDK_FILE + ".gz")).read_bytes()) != data:
        raise ValueError("Precision gzip mismatch")
    if any((directory / name).exists() for name in SNAPSHOTS):
        raise ValueError("Snapshot bypasses precision SDK")
    if clear_cache:
        for name in CACHES:
            (directory / name).unlink(missing_ok=True)
    return report


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path, nargs="?")
    parser.add_argument("--out", type=Path)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--install", type=Path, help="Patch an isolated image SDK directory")
    mode.add_argument("--verify-install", type=Path)
    parser.add_argument("--clear-cache", action="store_true", help="Only before server start")
    args = parser.parse_args()
    if args.install or args.verify_install:
        if args.source or args.out or (args.clear_cache and not args.verify_install):
            parser.error("Install/verify cannot be combined with copy arguments")
        print(
            json.dumps(
                install(args.install)
                if args.install
                else verify_install(args.verify_install, clear_cache=args.clear_cache)
            )
        )
    else:
        if not args.source or not args.out or args.clear_cache:
            parser.error("Copy mode requires source and --out")
        print(build(args.source, args.out))
